"""Voice prompt caching for Qwen3-TTS."""

from typing import Optional, Dict, Any
from datetime import datetime, timedelta
import logging

logger = logging.getLogger(__name__)


class QwenVoiceCache:
    """Cache for voice clone prompts to avoid re-extraction.
    
    This caches voice clone prompts generated by Qwen3-TTS, allowing
    fast reuse without re-extracting features. This is especially useful
    when generating multiple utterances with the same voice.
    """
    
    def __init__(self, ttl_minutes: int = 60):
        """Initialize voice cache.
        
        Args:
            ttl_minutes: Time-to-live for cached prompts in minutes (default: 60)
        """
        self.cache: Dict[str, Dict[str, Any]] = {}
        self.ttl = timedelta(minutes=ttl_minutes)
        logger.info(f"Voice cache initialized with TTL: {ttl_minutes} minutes")
    
    def get(self, voice_id: str) -> Optional[Any]:
        """Get cached prompt if valid.
        
        Args:
            voice_id: Unique identifier for the voice
            
        Returns:
            Cached voice clone prompt, or None if not found/expired
        """
        if voice_id in self.cache:
            entry = self.cache[voice_id]
            age = datetime.now() - entry["created_at"]
            
            if age < self.ttl:
                remaining = (self.ttl - age).total_seconds()
                logger.debug(f"Cache hit for '{voice_id}' (TTL: {remaining:.0f}s remaining)")
                return entry["prompt"]
            else:
                logger.debug(f"Cache expired for '{voice_id}' (age: {age.total_seconds():.0f}s)")
                del self.cache[voice_id]  # Expired
        
        logger.debug(f"Cache miss for '{voice_id}'")
        return None
    
    def set(self, voice_id: str, prompt: Any):
        """Cache a prompt.
        
        Args:
            voice_id: Unique identifier for the voice
            prompt: Voice clone prompt to cache
        """
        self.cache[voice_id] = {
            "prompt": prompt,
            "created_at": datetime.now()
        }
        logger.debug(f"Cached voice prompt for '{voice_id}'")
    
    def clear(self):
        """Clear all cache entries."""
        count = len(self.cache)
        self.cache.clear()
        logger.info(f"Cleared all {count} cached voice prompts")
    
    def invalidate(self, voice_id: str):
        """Remove specific voice from cache.
        
        Args:
            voice_id: Voice ID to remove from cache
        """
        if voice_id in self.cache:
            del self.cache[voice_id]
            logger.debug(f"Invalidated cache for '{voice_id}'")
        else:
            logger.debug(f"No cache entry to invalidate for '{voice_id}'")
    
    def get_stats(self) -> Dict[str, Any]:
        """Get cache statistics.
        
        Returns:
            Dictionary with cache statistics
        """
        return {
            "total_entries": len(self.cache),
            "ttl_minutes": self.ttl.total_seconds() / 60,
            "voice_ids": list(self.cache.keys())
        }